services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: catamorphic
      POSTGRES_PASSWORD: catamorphic
      POSTGRES_DB: catamorphic
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
