import type { AppApiEntry } from "@catamorphic/parser";
import { typeFromJsonSchema } from "./trigger-codegen.js";

/**
 * Generated typed app-api client interface, projected into each app
 * workspace from the parsed `workflows/src/app-api.ts` surface and the
 * workflows' extracted IO schemas. App code passes it to `createClient`:
 *
 * ```typescript
 * import { createClient } from "@catamorphic/app";
 * import type { ProjectAppApi } from "./catamorphic-app-api.js";
 * const workflows = createClient<ProjectAppApi>();
 * ```
 *
 * Lives under `apps/<name>/src` so the app tsconfig (`include: ["src"]`)
 * picks it up without configuration.
 */
export function appApiTypesPath(appName: string): string {
  return `apps/${appName}/src/catamorphic-app-api.d.ts`;
}

export function renderAppApiTypesModule(
  entries: readonly AppApiEntry[],
): string {
  const sorted = [...entries].sort((a, b) =>
    a.exposedName.localeCompare(b.exposedName),
  );
  const members = sorted.map((entry) => {
    const input = typeFromJsonSchema((entry.inputSchema ?? {}) as never, 2);
    const output = typeFromJsonSchema((entry.outputSchema ?? {}) as never, 2);
    return [
      `  ${propertyKey(entry.exposedName)}: Workflow<{`,
      `    input: ${input};`,
      `    output: ${output};`,
      `  }>;`,
    ].join("\n");
  });
  return [
    "// Generated by Catamorphic from workflows/src/app-api.ts and the",
    "// workflows' extracted input/output types. Do not edit — changes are",
    "// overwritten on the next sync.",
    "",
    'import type { Workflow } from "@catamorphic/app";',
    "",
    "export interface ProjectAppApi {",
    members.join("\n"),
    "}",
    "",
  ].join("\n");
}

function propertyKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}
