import path from "node:path";
import {
  type ProjectTriggerKind,
  resolveTriggerBinding,
  schemaHoles,
  typeFromJsonSchema,
} from "@catamorphic/parser";
import { PROJECT_WORKFLOWS_DIR } from "@catamorphic/workflow/project-layout";
import type { TriggerKindRuntime } from "./trigger-kinds.js";

/**
 * Conventional location of the generated trigger-kinds augmentation inside a
 * project workspace. Lives under `.work/workflows/src` so the workflows package
 * picks it up without tsconfig changes.
 */
export const TRIGGER_TYPES_SOURCE_PATH = `${PROJECT_WORKFLOWS_DIR}/src/work-triggers.d.ts`;

/**
 * Renders the module augmentation that projects `trigger()` calls type-check
 * against. Every generated file is a projection of code its owner writes —
 * the host's registered kinds and the project's own trigger kinds (ADR 0171),
 * whose payload types come from their modules — regenerated on change,
 * never hand-edited.
 */
export function renderTriggerTypesModule(input: {
  kinds: readonly TriggerKindRuntime[];
  projectKinds?: readonly ProjectTriggerKind[];
}): string {
  const sorted = [...input.kinds].sort((a, b) => a.name.localeCompare(b.name));
  const hostKinds = new Map(sorted.map((kind) => [kind.name, kind]));
  const projectKinds = [...(input.projectKinds ?? [])].sort((a, b) =>
    a.name.localeCompare(b.name),
  );
  const entries = sorted.map((kind) => {
    const payload = typeFromJsonSchema(kind.payloadJsonSchema, 3);
    const config = typeFromJsonSchema(kind.configJsonSchema, 3);
    const output =
      kind.outputJsonSchema !== undefined
        ? typeFromJsonSchema(kind.outputJsonSchema, 3)
        : undefined;
    return [
      ...docLines(kind.description),
      `    ${JSON.stringify(kind.name)}: {`,
      `      payload: ${payload};`,
      `      config: ${config};`,
      ...(output !== undefined ? [`      output: ${output};`] : []),
      `    };`,
    ].join("\n");
  });
  for (const kind of projectKinds) {
    const resolved = resolveTriggerBinding({
      binding: { kind: kind.name, config: {} },
      projectKinds,
    });
    const root = resolved.ok ? hostKinds.get(resolved.binding.kind) : undefined;
    const output =
      root?.outputJsonSchema !== undefined
        ? typeFromJsonSchema(root.outputJsonSchema, 3)
        : undefined;
    entries.push(
      [
        ...docLines(kind.description),
        `    ${JSON.stringify(kind.name)}: {`,
        `      payload: PayloadOf<typeof import(${JSON.stringify(moduleSpecifier(kind.filePath))}).${kind.exportName}>;`,
        "      config: Record<string, never>;",
        ...(output !== undefined ? [`      output: ${output};`] : []),
        `    };`,
      ].join("\n"),
    );
  }
  const body = entries.join("\n");
  // `Hole<Name>` marks a parameterized kind's open positions (ADR 0042);
  // the brand is only imported when some kind's schema declares one.
  const usesHoles = sorted.some(
    (kind) =>
      schemaHoles(kind.payloadJsonSchema).length > 0 ||
      (kind.outputJsonSchema !== undefined &&
        schemaHoles(kind.outputJsonSchema).length > 0),
  );
  const imports = [
    ...(usesHoles ? ["Hole"] : []),
    ...(projectKinds.length > 0 ? ["PayloadOf"] : []),
  ];
  return [
    "// Generated by Catamorphic from the host's registered trigger kinds",
    "// and the project's own in .work/triggers/.",
    "// Do not edit — changes are overwritten on the next sync.",
    "",
    ...(imports.length > 0
      ? [
          `import type { ${imports.join(", ")} } from "@catamorphic/workflow";`,
          "",
        ]
      : []),
    'declare module "@catamorphic/workflow" {',
    "  interface TriggerKinds {",
    body,
    "  }",
    "}",
    "",
    "export {};",
    "",
  ].join("\n");
}

function docLines(description: string | undefined): string[] {
  return description
    ? [`    /** ${description.replaceAll("*/", "*\\/")} */`]
    : [];
}

/** The trigger module as the generated file imports it. */
function moduleSpecifier(filePath: string): string {
  const relative = path.posix.relative(
    path.posix.dirname(TRIGGER_TYPES_SOURCE_PATH),
    filePath,
  );
  return relative.replace(/\.tsx?$/, "");
}
