import { schemaHoles, typeFromJsonSchema } from "@catamorphic/parser";
import type { TriggerKindRuntime } from "./trigger-kinds.js";

/**
 * Conventional location of the generated trigger-kinds augmentation inside a
 * project workspace. Lives under `workflows/src` so the workflows package
 * picks it up without tsconfig changes.
 */
export const TRIGGER_TYPES_SOURCE_PATH =
  "workflows/src/catamorphic-triggers.d.ts";

/**
 * Renders the module augmentation that projects `trigger()` calls type-check
 * against. Every generated file is a projection of the host's registered
 * kinds — regenerated on change, never hand-edited.
 */
export function renderTriggerTypesModule(
  kinds: readonly TriggerKindRuntime[],
): string {
  const sorted = [...kinds].sort((a, b) => a.name.localeCompare(b.name));
  const entries = sorted.map((kind) => {
    const payload = typeFromJsonSchema(kind.payloadJsonSchema, 3);
    const config = typeFromJsonSchema(kind.configJsonSchema, 3);
    const output =
      kind.outputJsonSchema !== undefined
        ? typeFromJsonSchema(kind.outputJsonSchema, 3)
        : undefined;
    const docLines = kind.description
      ? [`    /** ${kind.description.replaceAll("*/", "*\\/")} */`]
      : [];
    return [
      ...docLines,
      `    ${JSON.stringify(kind.name)}: {`,
      `      payload: ${payload};`,
      `      config: ${config};`,
      ...(output !== undefined ? [`      output: ${output};`] : []),
      `    };`,
    ].join("\n");
  });
  const body = entries.join("\n");
  // `Hole<Name>` marks a parameterized kind's open positions (ADR 0042);
  // the brand is only imported when some kind's schema declares one.
  const usesHoles = sorted.some(
    (kind) =>
      schemaHoles(kind.payloadJsonSchema).length > 0 ||
      (kind.outputJsonSchema !== undefined &&
        schemaHoles(kind.outputJsonSchema).length > 0),
  );
  return [
    "// Generated by Catamorphic from the host's registered trigger kinds.",
    "// Do not edit — changes are overwritten on the next sync.",
    "",
    ...(usesHoles
      ? ['import type { Hole } from "@catamorphic/workflow";', ""]
      : []),
    'declare module "@catamorphic/workflow" {',
    "  interface TriggerKinds {",
    body,
    "  }",
    "}",
    "",
    "export {};",
    "",
  ].join("\n");
}
