-- The Work server's host tables carry its product prefix (ADR 0160).
ALTER TABLE stock_project_access_requests RENAME TO work_project_access_requests;
ALTER TABLE work_project_access_requests RENAME CONSTRAINT stock_project_access_requests_status_check TO work_project_access_requests_status_check;
ALTER TABLE work_project_access_requests RENAME CONSTRAINT stock_project_access_requests_pkey TO work_project_access_requests_pkey;
ALTER TABLE work_project_access_requests RENAME CONSTRAINT stock_project_access_requests_project_id_fkey TO work_project_access_requests_project_id_fkey;
ALTER INDEX idx_stock_project_access_requests_project_status RENAME TO idx_work_project_access_requests_project_status;
ALTER INDEX uq_stock_project_access_requests_pending RENAME TO uq_work_project_access_requests_pending;

ALTER TABLE stock_project_admission_policies RENAME TO work_project_admission_policies;
ALTER TABLE work_project_admission_policies RENAME CONSTRAINT stock_project_admission_policies_mode_check TO work_project_admission_policies_mode_check;
ALTER TABLE work_project_admission_policies RENAME CONSTRAINT stock_project_admission_policies_pkey TO work_project_admission_policies_pkey;
ALTER TABLE work_project_admission_policies RENAME CONSTRAINT stock_project_admission_policies_project_id_fkey TO work_project_admission_policies_project_id_fkey;

ALTER TABLE stock_project_invitations RENAME TO work_project_invitations;
ALTER TABLE work_project_invitations RENAME CONSTRAINT stock_project_invitations_pkey TO work_project_invitations_pkey;
ALTER TABLE work_project_invitations RENAME CONSTRAINT stock_project_invitations_project_id_fkey TO work_project_invitations_project_id_fkey;
ALTER INDEX idx_stock_project_invitations_project RENAME TO idx_work_project_invitations_project;
