-- Leave free space on execution_jobs pages so heartbeats stay HOT.
--
-- Migration 028 removed the index that was blocking HOT updates, but HOT also
-- requires room for the new tuple on the same page as the old one. At the
-- default fillfactor of 100 an insert-churned queue table has no such room, so
-- heartbeats fall back to ordinary updates and the write amplification 028
-- removed comes straight back. The integration test for 028 only measures 100%
-- HOT because it VACUUMs first, which manufactures the free space this setting
-- makes permanent.
--
-- 85 costs ~18% more pages for the live set in exchange for keeping the ~90x
-- reduction in dead tuples under steady insert load. The table is small
-- relative to the run history it points at, so the space is worth it.
-- Migrations run inside a transaction, so the table is not rewritten here:
-- VACUUM FULL cannot run in one, and it takes an ACCESS EXCLUSIVE lock that
-- would stall every worker mid-deploy. Existing pages keep their current
-- packing and new writes honour the setting, so the benefit arrives as the
-- queue turns over — which for a queue table is quickly.
ALTER TABLE execution_jobs SET (fillfactor = 85);
