import {
  BadgeCheck,
  Bell,
  CalendarClock,
  CircleAlert,
  CircleSlash2,
  Clock,
  CodeXml,
  Cog,
  Crown,
  Database,
  FileText,
  Globe2,
  Inbox,
  Layers3,
  type LucideIcon,
  Mail,
  MessagesSquare,
  Search,
  Settings,
  Shield,
  Sparkles,
  SquareTerminal,
  Star,
  Timer,
  TriangleAlert,
  Truck,
  UserCheck,
  UserPlus,
  WandSparkles,
  Webhook,
  Wrench,
  Zap,
} from "lucide-react";

const ICONS: Readonly<Record<string, LucideIcon>> = {
  "alert-circle": CircleAlert,
  "alert-triangle": TriangleAlert,
  "badge-check": BadgeCheck,
  bell: Bell,
  calendar: CalendarClock,
  "circle-slash-2": CircleSlash2,
  clock: Clock,
  code: CodeXml,
  crown: Crown,
  database: Database,
  file: FileText,
  globe: Globe2,
  inbox: Inbox,
  layers: Layers3,
  mail: Mail,
  "messages-square": MessagesSquare,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  terminal: SquareTerminal,
  timer: Timer,
  truck: Truck,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "wand-sparkles": WandSparkles,
  webhook: Webhook,
  wrench: Wrench,
  zap: Zap,
};

export function NodeIcon({ name }: { name?: string }) {
  const Icon = ICONS[name ?? ""] ?? Cog;
  return <Icon aria-hidden="true" size={18} strokeWidth={1.8} />;
}
