import type { FastifyInstance } from "fastify";

/** What every machine installs from this control plane (ADR 0204). */
export interface InstallTarget {
  /** The control plane's public origin the worker dials. */
  controlPlaneUrl: string;
  /** The worker image, normally this server's own release. */
  image: string;
}

/**
 * The install target, or why machines cannot install from this server: a
 * worker image is needed (the published image's own, or
 * `WORK_WORKER_IMAGE`), and a public origin other machines reach.
 */
export function installTarget(args: {
  publicBase: string;
  workerImage?: string;
}): { target: InstallTarget } | { unavailable: string } {
  if (!args.workerImage)
    return {
      unavailable:
        "This server does not know which worker image machines should run. Set WORK_WORKER_IMAGE to the Work server image of this release (for example ghcr.io/<owner>/work-server:<version>).",
    };
  if (isLoopback(args.publicBase))
    return {
      unavailable:
        "Machines cannot reach this server at a loopback address. Set WORK_PUBLIC_URL to the HTTPS origin workers dial.",
    };
  return {
    target: { controlPlaneUrl: args.publicBase, image: args.workerImage },
  };
}

/** The data directory the script uses unless told otherwise. */
export const DEFAULT_WORKER_DATA_DIR = "/var/lib/work";

/**
 * The worker install script (ADR 0204): a POSIX sh script with the control
 * plane and image baked in, holding no secret. It installs Docker where it
 * is missing; with no usable `/dev/kvm` it installs gVisor and registers
 * the `runsc` runtime with Work's arguments (ADR 0203); then it runs the
 * worker image with `WORK_SANDBOX=auto`, the Docker socket, `/dev/kvm` when
 * present, and its data directory mounted at the same path.
 *
 * microsandbox runs each microVM through libkrun, which only opens
 * `/dev/kvm` and keeps the guest's network in user space: the device and
 * its group are all the worker container needs, never `--privileged` or
 * added capabilities.
 *
 * Downloads land in files that are checked before use, never piped into a
 * shell. Package installation waits, within bounds, for another one to
 * finish, as on a cloud machine's first boot. The data directory, which is
 * made private to the worker, is never a system directory.
 */
export function workerInstallScript(target: InstallTarget): string {
  return `#!/bin/sh
# Installs a Work worker on this machine (ADR 0204), generated by the Work
# server at ${target.controlPlaneUrl}. It holds no secret; run it as root:
#
#   curl -fsSL ${target.controlPlaneUrl}/api/workers/install.sh | sudo sh -s -- --code <enrollment code>
#
# Running it again is safe: it keeps what is installed and replaces the
# worker container, which keeps its enrollment in its data directory.
set -eu
# A failed download in a pipeline fails the script where the shell can say so.
# shellcheck disable=SC3040
if (set -o pipefail) 2>/dev/null; then set -o pipefail; fi

CONTROL_PLANE_URL=${shellQuote(target.controlPlaneUrl)}
IMAGE=${shellQuote(target.image)}
DATA_DIR=${DEFAULT_WORKER_DATA_DIR}
NAME=work-worker
CODE=

say() { printf 'work: %s\\n' "$*"; }
fail() {
  printf 'work: %s\\n' "$*" >&2
  exit 1
}
usage() {
  cat <<'USAGE'
Usage: install.sh --code <code> [--image <image>] [--data-dir <dir>] [--name <name>]

  --code <code>      the one-time enrollment code from the Work server (required)
  --image <image>    the worker image (default: this server's release)
  --data-dir <dir>   where the worker keeps its credential, sandboxes and
                     members' sign-ins (default: ${DEFAULT_WORKER_DATA_DIR}): a new
                     directory, or one under /var/lib, /srv, /opt, /data or
                     /home/<user> that is empty or a worker's
  --name <name>      the worker container's name (default: work-worker)
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --code | --image | --data-dir | --name)
      [ "$#" -ge 2 ] || fail "$1 needs a value"
      case "$1" in
        --code) CODE=$2 ;;
        --image) IMAGE=$2 ;;
        --data-dir) DATA_DIR=$2 ;;
        --name) NAME=$2 ;;
      esac
      shift 2
      ;;
    --code=*) CODE=\${1#--code=}; shift ;;
    --image=*) IMAGE=\${1#--image=}; shift ;;
    --data-dir=*) DATA_DIR=\${1#--data-dir=}; shift ;;
    --name=*) NAME=\${1#--name=}; shift ;;
    -h | --help) usage; exit 0 ;;
    *) usage >&2; fail "Unknown option: $1" ;;
  esac
done

# The data directory is handed to the worker's user and made private, so it
# is never a system directory: a new one, or an empty or worker's one under
# a place meant for data.
case "$DATA_DIR" in
  /) ;;
  */) DATA_DIR=\${DATA_DIR%/} ;;
esac
data_dir_allowed() {
  case "$1" in
    /*) ;;
    *) return 1 ;;
  esac
  case "$1" in
    *//* | */./* | */../* | */. | */..) return 1 ;;
    / | /bin | /boot | /dev | /etc | /home | /lib | /lib32 | /lib64 | /libx32 | \\
      /media | /mnt | /opt | /proc | /root | /run | /sbin | /snap | /srv | \\
      /sys | /tmp | /usr | /var | /var/cache | /var/lib | /var/log | \\
      /var/mail | /var/run | /var/spool | /var/tmp)
      return 1 ;;
    /bin/* | /boot/* | /dev/* | /etc/* | /lib/* | /lib32/* | /lib64/* | \\
      /libx32/* | /proc/* | /root/* | /run/* | /sbin/* | /sys/* | /usr/*)
      return 1 ;;
  esac
  [ -e "$1" ] || return 0
  [ -d "$1" ] || return 1
  [ -f "$1/worker-credential" ] && return 0
  case "$1" in
    /var/lib/?* | /srv/?* | /opt/?* | /data | /data/?* | /home/?*/?*)
      [ -z "$(ls -A "$1")" ] ;;
    *) return 1 ;;
  esac
}

[ -n "$CODE" ] || fail "Pass the enrollment code: --code <code>"
[ "$(id -u)" -eq 0 ] || fail "Run this script as root, for example with sudo sh"
data_dir_allowed "$DATA_DIR" ||
  fail "--data-dir $DATA_DIR is not a place for the worker's data: use a new directory, or an empty one under /var/lib, /srv, /opt, /data or /home/<user>"
case "$NAME" in
  [a-zA-Z0-9]*) ;;
  *) fail "--name must start with a letter or digit" ;;
esac

WORK_TMP=$(mktemp -d)
trap 'rm -rf "$WORK_TMP"' EXIT

# Download a file, and check it is there before it is used.
download() {
  curl -fsSL --retry 3 --connect-timeout 20 "$1" -o "$2" ||
    fail "Could not download $1"
  [ -s "$2" ] || fail "$1 answered with nothing"
}

# On a first boot, cloud-init and unattended upgrades may be installing
# packages: wait for them, within bounds, before installing ours.
apt_busy() {
  command -v fuser >/dev/null 2>&1 || return 1
  fuser /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock \\
    /var/lib/apt/lists/lock >/dev/null 2>&1
}
wait_for_apt() {
  waited=0
  while apt_busy; do
    if [ "$waited" -eq 0 ]; then
      say "Waiting for another package installation to finish"
    fi
    waited=$((waited + 1))
    [ "$waited" -le 60 ] ||
      fail "Another package installation held apt's lock for ten minutes; run this script again later"
    sleep 10
  done
}
apt_get() {
  tries=0
  wait_for_apt
  until DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=300 "$@"; do
    tries=$((tries + 1))
    [ "$tries" -lt 20 ] || fail "apt-get $1 kept failing"
    say "apt-get $1 failed, perhaps behind another installation; trying again"
    sleep 15
    wait_for_apt
  done
}

# Docker, with the official convenience script when it is missing.
if ! command -v docker >/dev/null 2>&1; then
  command -v curl >/dev/null 2>&1 || fail "Install curl, then run this script again"
  say "Installing Docker"
  download https://get.docker.com "$WORK_TMP/get-docker.sh"
  case "$(head -n 1 "$WORK_TMP/get-docker.sh")" in
    '#!'*sh*) ;;
    *) fail "https://get.docker.com did not answer with Docker's install script" ;;
  esac
  tries=0
  until wait_for_apt && sh "$WORK_TMP/get-docker.sh"; do
    tries=$((tries + 1))
    [ "$tries" -lt 3 ] || fail "Docker's install script failed"
    say "Docker's install script failed; trying again"
    sleep 15
  done
fi
if command -v systemctl >/dev/null 2>&1; then
  systemctl enable --now docker >/dev/null 2>&1 || true
fi
docker info >/dev/null 2>&1 || fail "Docker is installed but its daemon does not answer"

restart_docker() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl restart docker
  else
    service docker restart
  fi
}

# Isolation: microVMs where KVM is usable, gVisor everywhere else.
KVM=0
if [ -c /dev/kvm ] && [ -r /dev/kvm ] && [ -w /dev/kvm ]; then
  KVM=1
  say "KVM is available: agents run in microVMs"
else
  if ! command -v runsc >/dev/null 2>&1; then
    command -v apt-get >/dev/null 2>&1 ||
      fail "This machine has no KVM and no apt-get. Install gVisor (https://gvisor.dev/docs/user_guide/install/), then run this script again"
    say "No KVM: installing gVisor"
    apt_get update -qq
    apt_get install -y -qq ca-certificates curl gnupg >/dev/null
    download https://gvisor.dev/archive.key "$WORK_TMP/gvisor.key"
    grep -q 'BEGIN PGP PUBLIC KEY BLOCK' "$WORK_TMP/gvisor.key" ||
      fail "https://gvisor.dev/archive.key is not a signing key"
    gpg --dearmor --yes -o /usr/share/keyrings/gvisor-archive-keyring.gpg \\
      "$WORK_TMP/gvisor.key"
    ARCH=$(dpkg --print-architecture)
    echo "deb [arch=$ARCH signed-by=/usr/share/keyrings/gvisor-archive-keyring.gpg] https://storage.googleapis.com/gvisor/releases release main" \\
      >/etc/apt/sources.list.d/gvisor.list
    apt_get update -qq
    apt_get install -y -qq runsc >/dev/null
  fi
  # Sandboxes reach their egress proxy over a host socket and run nested
  # Docker with raw sockets (ADR 0203). runsc merges its runtime into the
  # daemon's configuration; Docker restarts only when that changed.
  BEFORE=$(cksum /etc/docker/daemon.json 2>/dev/null || true)
  runsc install -- --host-uds=open --net-raw
  AFTER=$(cksum /etc/docker/daemon.json 2>/dev/null || true)
  if [ "$BEFORE" != "$AFTER" ]; then
    say "Restarting Docker with the gVisor runtime"
    restart_docker
  fi
  RUNTIMES=$(docker info --format '{{json .Runtimes}}')
  case "$RUNTIMES" in
    *'"runsc"'*) ;;
    *) fail "Docker did not load the runsc runtime; see /etc/docker/daemon.json" ;;
  esac
  say "gVisor is ready: agents run in gVisor sandboxes"
fi

# The worker's data directory belongs to the image's user (uid 1000).
mkdir -p "$DATA_DIR"
chown 1000:1000 "$DATA_DIR"
chmod 0700 "$DATA_DIR"

say "Pulling $IMAGE"
docker pull "$IMAGE" >/dev/null
if docker container inspect "$NAME" >/dev/null 2>&1; then
  say "Replacing the existing $NAME container"
  docker rm -f "$NAME" >/dev/null
fi

# The data directory is mounted at the same path, so the Docker daemon
# mounts what the worker writes there into its sandboxes.
set -- --detach --name "$NAME" --restart unless-stopped \\
  --volume "$DATA_DIR:$DATA_DIR" --env "WORK_DATA_DIR=$DATA_DIR" \\
  --volume /var/run/docker.sock:/var/run/docker.sock \\
  --group-add "$(stat -c %g /var/run/docker.sock)" \\
  --env "WORK_CONTROL_PLANE_URL=$CONTROL_PLANE_URL" \\
  --env "WORK_WORKER_ENROLLMENT=$CODE" \\
  --env WORK_SANDBOX=auto
if [ "$KVM" = 1 ]; then
  set -- "$@" --device /dev/kvm --group-add "$(stat -c %g /dev/kvm)"
fi
docker run "$@" "$IMAGE" bun apps/server/src/worker.ts >/dev/null

say "The worker is running as the container $NAME and connects to $CONTROL_PLANE_URL."
say "Follow it with: docker logs -f $NAME"
say "Its state: docker ps --filter name=$NAME"
`;
}

/** Where cloud-init writes the script on a cloud machine. */
export const CLOUD_INIT_SCRIPT_PATH = "/usr/local/sbin/work-install-worker";

/**
 * Cloud-init user data for a cloud machine (ADR 0204): the install script
 * itself, written to disk and run once with the machine's enrollment code.
 * Nothing is fetched over the network to start it.
 */
export function workerCloudInit(args: {
  script: string;
  code: string;
}): string {
  const command = ["sh", CLOUD_INIT_SCRIPT_PATH, "--code", args.code]
    .map((part) => JSON.stringify(part))
    .join(", ");
  return [
    "#cloud-config",
    "write_files:",
    `  - path: ${CLOUD_INIT_SCRIPT_PATH}`,
    "    owner: root:root",
    `    permissions: "0700"`,
    "    encoding: b64",
    `    content: ${Buffer.from(args.script).toString("base64")}`,
    "runcmd:",
    `  - [${command}]`,
    "",
  ].join("\n");
}

/**
 * `GET /api/workers/install.sh`, public: what a machine runs to become a
 * worker. Answers 503 naming what is missing when machines cannot install
 * from this server.
 */
export function registerInstallScriptRoute(
  app: FastifyInstance,
  install: { target: InstallTarget } | { unavailable: string },
): void {
  app.get("/api/workers/install.sh", async (_request, reply) => {
    if ("unavailable" in install)
      return reply
        .status(503)
        .type("text/plain; charset=utf-8")
        .send(`${install.unavailable}\n`);
    return reply
      .type("text/x-shellscript; charset=utf-8")
      .header("cache-control", "no-store")
      .send(workerInstallScript(install.target));
  });
}

/** Single-quoted for sh: safe whatever the value holds. */
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function isLoopback(base: string): boolean {
  const { hostname } = new URL(base);
  return (
    hostname === "127.0.0.1" || hostname === "localhost" || hostname === "[::1]"
  );
}
