import type { FastifyInstance } from "fastify";

/** Where the worker image is published (ADR 0159). */
export const WORK_IMAGE_REPOSITORY = "ghcr.io/opencx-labs/work-server";

/** What every machine installs from this control plane (ADR 0204). */
export interface InstallTarget {
  /** The control plane's public origin the worker dials. */
  controlPlaneUrl: string;
  /** The worker image, normally this server's own release. */
  image: string;
}

/**
 * The install target, or why machines cannot install from this server: a
 * worker image is needed (this release's, or `WORK_WORKER_IMAGE`), and a
 * public origin other machines reach.
 */
export function installTarget(args: {
  publicBase: string;
  workerImage?: string;
}): { target: InstallTarget } | { unavailable: string } {
  if (!args.workerImage)
    return {
      unavailable:
        "This server does not know which worker image machines should run. Set WORK_WORKER_IMAGE to the Work server image of this release (for example ghcr.io/opencx-labs/work-server:<version>).",
    };
  if (isLoopback(args.publicBase))
    return {
      unavailable:
        "Machines cannot reach this server at a loopback address. Set WORK_PUBLIC_URL to the HTTPS origin workers dial.",
    };
  return {
    target: { controlPlaneUrl: args.publicBase, image: args.workerImage },
  };
}

/** The data directory the script uses unless told otherwise. */
export const DEFAULT_WORKER_DATA_DIR = "/var/lib/work";

/**
 * The worker install script (ADR 0204): a POSIX sh script with the control
 * plane and image baked in, holding no secret. It installs Docker where it
 * is missing; with no usable `/dev/kvm` it installs gVisor and registers
 * the `runsc` runtime with Work's arguments (ADR 0203); then it runs the
 * worker image with `WORK_SANDBOX=auto`, the Docker socket, `/dev/kvm` when
 * present, and its data directory mounted at the same path.
 *
 * microsandbox runs each microVM through libkrun, which only opens
 * `/dev/kvm` and keeps the guest's network in user space: the device and
 * its group are all the worker container needs, never `--privileged` or
 * added capabilities.
 */
export function workerInstallScript(target: InstallTarget): string {
  return `#!/bin/sh
# Installs a Work worker on this machine (ADR 0204), generated by the Work
# server at ${target.controlPlaneUrl}. It holds no secret; run it as root:
#
#   curl -fsSL ${target.controlPlaneUrl}/api/workers/install.sh | sudo sh -s -- --code <enrollment code>
#
# Running it again is safe: it keeps what is installed and replaces the
# worker container, which keeps its enrollment in its data directory.
set -eu

CONTROL_PLANE_URL=${shellQuote(target.controlPlaneUrl)}
IMAGE=${shellQuote(target.image)}
DATA_DIR=${DEFAULT_WORKER_DATA_DIR}
NAME=work-worker
CODE=

say() { printf 'work: %s\\n' "$*"; }
fail() {
  printf 'work: %s\\n' "$*" >&2
  exit 1
}
usage() {
  cat <<'USAGE'
Usage: install.sh --code <code> [--image <image>] [--data-dir <dir>] [--name <name>]

  --code <code>      the one-time enrollment code from the Work server (required)
  --image <image>    the worker image (default: this server's release)
  --data-dir <dir>   where the worker keeps its credential, sandboxes and
                     members' sign-ins (default: ${DEFAULT_WORKER_DATA_DIR})
  --name <name>      the worker container's name (default: work-worker)
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --code | --image | --data-dir | --name)
      [ "$#" -ge 2 ] || fail "$1 needs a value"
      case "$1" in
        --code) CODE=$2 ;;
        --image) IMAGE=$2 ;;
        --data-dir) DATA_DIR=$2 ;;
        --name) NAME=$2 ;;
      esac
      shift 2
      ;;
    --code=*) CODE=\${1#--code=}; shift ;;
    --image=*) IMAGE=\${1#--image=}; shift ;;
    --data-dir=*) DATA_DIR=\${1#--data-dir=}; shift ;;
    --name=*) NAME=\${1#--name=}; shift ;;
    -h | --help) usage; exit 0 ;;
    *) usage >&2; fail "Unknown option: $1" ;;
  esac
done

[ -n "$CODE" ] || fail "Pass the enrollment code: --code <code>"
[ "$(id -u)" -eq 0 ] || fail "Run this script as root, for example with sudo sh"
case "$DATA_DIR" in
  /*) ;;
  *) fail "--data-dir must be an absolute path" ;;
esac
case "$NAME" in
  [a-zA-Z0-9]*) ;;
  *) fail "--name must start with a letter or digit" ;;
esac

# Docker, with the official convenience script when it is missing.
if ! command -v docker >/dev/null 2>&1; then
  command -v curl >/dev/null 2>&1 || fail "Install curl, then run this script again"
  say "Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi
if command -v systemctl >/dev/null 2>&1; then
  systemctl enable --now docker >/dev/null 2>&1 || true
fi
docker info >/dev/null 2>&1 || fail "Docker is installed but its daemon does not answer"

restart_docker() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl restart docker
  else
    service docker restart
  fi
}

# Isolation: microVMs where KVM is usable, gVisor everywhere else.
KVM=0
if [ -c /dev/kvm ] && [ -r /dev/kvm ] && [ -w /dev/kvm ]; then
  KVM=1
  say "KVM is available: agents run in microVMs"
else
  if ! command -v runsc >/dev/null 2>&1; then
    command -v apt-get >/dev/null 2>&1 ||
      fail "This machine has no KVM and no apt-get. Install gVisor (https://gvisor.dev/docs/user_guide/install/), then run this script again"
    say "No KVM: installing gVisor"
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq ca-certificates curl gnupg >/dev/null
    curl -fsSL https://gvisor.dev/archive.key |
      gpg --dearmor --yes -o /usr/share/keyrings/gvisor-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gvisor-archive-keyring.gpg] https://storage.googleapis.com/gvisor/releases release main" \\
      >/etc/apt/sources.list.d/gvisor.list
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq runsc >/dev/null
  fi
  # Sandboxes reach their egress proxy over a host socket and run nested
  # Docker with raw sockets (ADR 0203). runsc merges its runtime into the
  # daemon's configuration; Docker restarts only when that changed.
  BEFORE=$(cksum /etc/docker/daemon.json 2>/dev/null || true)
  runsc install -- --host-uds=open --net-raw
  AFTER=$(cksum /etc/docker/daemon.json 2>/dev/null || true)
  if [ "$BEFORE" != "$AFTER" ]; then
    say "Restarting Docker with the gVisor runtime"
    restart_docker
  fi
  docker info --format '{{json .Runtimes}}' | grep -q '"runsc"' ||
    fail "Docker did not load the runsc runtime; see /etc/docker/daemon.json"
  say "gVisor is ready: agents run in gVisor sandboxes"
fi

# The worker's data directory belongs to the image's user (uid 1000).
mkdir -p "$DATA_DIR"
chown 1000:1000 "$DATA_DIR"
chmod 0700 "$DATA_DIR"

say "Pulling $IMAGE"
docker pull "$IMAGE" >/dev/null
if docker container inspect "$NAME" >/dev/null 2>&1; then
  say "Replacing the existing $NAME container"
  docker rm -f "$NAME" >/dev/null
fi

# The data directory is mounted at the same path, so the Docker daemon
# mounts what the worker writes there into its sandboxes.
set -- --detach --name "$NAME" --restart unless-stopped \\
  --volume "$DATA_DIR:$DATA_DIR" --env "WORK_DATA_DIR=$DATA_DIR" \\
  --volume /var/run/docker.sock:/var/run/docker.sock \\
  --group-add "$(stat -c %g /var/run/docker.sock)" \\
  --env "WORK_CONTROL_PLANE_URL=$CONTROL_PLANE_URL" \\
  --env "WORK_WORKER_ENROLLMENT=$CODE" \\
  --env WORK_SANDBOX=auto
if [ "$KVM" = 1 ]; then
  set -- "$@" --device /dev/kvm --group-add "$(stat -c %g /dev/kvm)"
fi
docker run "$@" "$IMAGE" bun apps/server/src/worker.ts >/dev/null

say "The worker is running as the container $NAME and connects to $CONTROL_PLANE_URL."
say "Follow it with: docker logs -f $NAME"
say "Its state: docker ps --filter name=$NAME"
`;
}

/** Where cloud-init writes the script on a cloud machine. */
export const CLOUD_INIT_SCRIPT_PATH = "/usr/local/sbin/work-install-worker";

/**
 * Cloud-init user data for a cloud machine (ADR 0204): the install script
 * itself, written to disk and run once with the machine's enrollment code.
 * Nothing is fetched over the network to start it.
 */
export function workerCloudInit(args: {
  script: string;
  code: string;
}): string {
  const command = ["sh", CLOUD_INIT_SCRIPT_PATH, "--code", args.code]
    .map((part) => JSON.stringify(part))
    .join(", ");
  return [
    "#cloud-config",
    "write_files:",
    `  - path: ${CLOUD_INIT_SCRIPT_PATH}`,
    "    owner: root:root",
    `    permissions: "0700"`,
    "    encoding: b64",
    `    content: ${Buffer.from(args.script).toString("base64")}`,
    "runcmd:",
    `  - [${command}]`,
    "",
  ].join("\n");
}

/**
 * `GET /api/workers/install.sh`, public: what a machine runs to become a
 * worker. Answers 503 naming what is missing when machines cannot install
 * from this server.
 */
export function registerInstallScriptRoute(
  app: FastifyInstance,
  install: { target: InstallTarget } | { unavailable: string },
): void {
  app.get("/api/workers/install.sh", async (_request, reply) => {
    if ("unavailable" in install)
      return reply
        .status(503)
        .type("text/plain; charset=utf-8")
        .send(`${install.unavailable}\n`);
    return reply
      .type("text/x-shellscript; charset=utf-8")
      .header("cache-control", "no-store")
      .send(workerInstallScript(install.target));
  });
}

/** Single-quoted for sh: safe whatever the value holds. */
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function isLoopback(base: string): boolean {
  const { hostname } = new URL(base);
  return (
    hostname === "127.0.0.1" || hostname === "localhost" || hostname === "[::1]"
  );
}
